title: Divyanshu Tambi
<img src="assets/imgs/Passport size Photo.jpg" alt="Description" width="300" height="200">
description: Game Developer
# show_downloads: true
theme: jekyll-theme-minimal
# contact: 7023279762
